#### Import dependencies:

In [25]:
import sys #access to system parameters https://docs.python.org/3/library/sys.html
print("Python version: {}". format(sys.version))

import pandas as pd #collection of functions for data processing and analysis modeled after R dataframes with SQL like features
print("pandas version: {}". format(pd.__version__))

import matplotlib #collection of functions for scientific and publication-ready visualization
import matplotlib as plt
print("matplotlib version: {}". format(matplotlib.__version__))

import numpy as np #foundational package for scientific computing
print("NumPy version: {}". format(np.__version__))

import scipy as sp #collection of functions for scientific computing and advance mathematics
print("SciPy version: {}". format(sp.__version__)) 

import IPython
from IPython import display #pretty printing of dataframes in Jupyter notebook
print("IPython version: {}". format(IPython.__version__)) 

import sklearn #collection of machine learning algorithms
print("scikit-learn version: {}". format(sklearn.__version__))

#misc libraries
import random
import time
#ignore warnings
import warnings
warnings.filterwarnings('ignore')
print('-'*25)
import re
import os
import matplotlib.pyplot as plt
%matplotlib inline

Python version: 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ]
pandas version: 1.1.3
matplotlib version: 3.3.2
NumPy version: 1.19.5
SciPy version: 1.5.2
IPython version: 7.19.0
scikit-learn version: 0.23.2
-------------------------

#### Download data file if it has not been downloaded already:

In [26]:
#url = 'https://data.cityofnewyork.us/api/views/qgea-i56i/rows.csv?accessType=DOWNLOAD'
fn_src = 'https://data.cityofnewyork.us/api/views/bqiq-cu78/rows.csv?accessType=DOWNLOAD'
fn_dst = 'NYPD-Hate-Crimes.csv'

from six.moves import urllib

if os.path.isfile(fn_dst):
    print('File %s has already been downloaded' % fn_dst)
else:
    print('Fetching file %s[2.4GB]. This may take a while...' % fn_dst)
    urllib.request.urlretrieve(fn_src, fn_dst)
    print('File %s has been downloaded' % fn_dst)

File NYPD-Hate-Crimes.csv has already been downloaded

#### Open a stream to the data file so we don't have to load the whole data set into main memory

In [27]:
from openclean.pipeline import stream
ds_full = stream(fn_dst)

In [28]:
print(f'The dataset contains {ds_full.count():,} rows.')

The dataset contains 1,181 rows.

In [29]:
ds_full.head()

,Full Complaint ID,Complaint Year Number,Month Number,Record Create Date,Complaint Precinct Code,Patrol Borough Name,County,Law Code Category Description,Offense Description,PD Code Description,Bias Motive Description,Offense Category,Arrest Date,Arrest Id
0,201904612204817,2019,2,02/08/2019,46,PATROL BORO BRONX,BRONX,FELONY,FELONY ASSAULT,"ASSAULT 2,1,UNCLASSIFIED",ANTI-MALE HOMOSEXUAL (GAY),Sexual Orientation,02/08/2019,B31678218
1,201904812229517,2019,3,03/09/2019,48,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-WHITE,Race/Color,03/09/2019,B31682790
2,201904812226617,2019,3,03/08/2019,48,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-WHITE,Race/Color,03/09/2019,B31682806
3,201904812231317,2019,3,03/10/2019,48,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,ASSAULT 3,ANTI-WHITE,Race/Color,03/09/2019,B31682806
4,201904212405517,2019,5,05/11/2019,42,PATROL BORO BRONX,BRONX,FELONY,ROBBERY,"ROBBERY,POCKETBOOK/CARRIED BAG",ANTI-MUSLIM,Religion/Religious Practice,05/10/2019,B31692174
5,201904212405517,2019,5,05/11/2019,42,PATROL BORO BRONX,BRONX,FELONY,ROBBERY,"ROBBERY,POCKETBOOK/CARRIED BAG",ANTI-MUSLIM,Religion/Religious Practice,05/10/2019,B31692175
6,201904212405517,2019,5,05/11/2019,42,PATROL BORO BRONX,BRONX,FELONY,ROBBERY,"ROBBERY,POCKETBOOK/CARRIED BAG",ANTI-MUSLIM,Religion/Religious Practice,05/10/2019,B31692176
7,201904012711317,2019,6,06/01/2019,40,PATROL BORO BRONX,BRONX,FELONY,RAPE,RAPE 1,ANTI-WHITE,Race/Color,06/14/2019,B31697030
8,201904912495217,2019,7,07/09/2019,49,PATROL BORO BRONX,BRONX,FELONY,FELONY ASSAULT,"ASSAULT 2,1,UNCLASSIFIED",ANTI-HISPANIC,Ethnicity/National Origin/Ancestry,07/21/2019,B31702150
9,201904712851617,2019,8,08/05/2019,47,PATROL BORO BRONX,BRONX,MISDEMEANOR,ASSAULT 3 & RELATED OFFENSES,"MENACING,UNCLASSIFIED",ANTI-TRANSGENDER,Gender,08/05/2019,B31704341

#### Use openclean to profile the data set:

In [30]:
from openclean.profiling.column import DefaultColumnProfiler

#profiles = ds.profile(default_profiler=DefaultColumnProfiler)
profiles = ds_full.profile(default_profiler=DefaultColumnProfiler)

In [31]:
profiles.stats()

                               total  empty  distinct  uniqueness    entropy
Full Complaint ID               1181      0      1102    0.933108  10.055231
Complaint Year Number           1181      0         3    0.002540   1.555348
Month Number                    1181      0        12    0.010161   3.529311
Record Create Date              1181      0       609    0.515665   8.973195
Complaint Precinct Code         1181      0        76    0.064352   5.960441
Patrol Borough Name             1181      0         8    0.006774   2.830716
County                          1181      0         5    0.004234   1.984774
Law Code Category Description   1181      0         4    0.003387   1.093351
Offense Description             1181      0        17    0.014395   2.641960
PD Code Description             1181      0        50    0.042337   3.476055
Bias Motive Description         1181      0        23    0.019475   2.745725
Offense Category                1181      0         8    0.006774   1.821166
Arrest Date                     1181    784       237    0.596977   7.547864
Arrest Id                       1181    784       396    0.997481   8.627957

In [32]:
# Print the most frequent data type for each column.

print('Schema\n------')
for col in ds_full.columns:
    p = profiles.column(col)
    print("  '{}' ({})".format(col, p['datatypes']['distinct'].most_common(1)[0][0]))

Schema
------
  'Full Complaint ID' (int)
  'Complaint Year Number' (int)
  'Month Number' (int)
  'Record Create Date' (date)
  'Complaint Precinct Code' (int)
  'Patrol Borough Name' (str)
  'County' (str)
  'Law Code Category Description' (str)
  'Offense Description' (str)
  'PD Code Description' (str)
  'Bias Motive Description' (str)
  'Offense Category' (str)
  'Arrest Date' (date)
  'Arrest Id' (str)

### Field Name & Description:
    'CMPLNT_NUM' (int)                 Complaint Number
    'CMPLNT_FR_DT' (date)              Complaint From Date
    'CMPLNT_FR_TM' (date)              Complaint From Time
    'CMPLNT_TO_DT' (date)              Complaint To Date
    'CMPLNT_TO_TM' (date)              Complaint To Time
    'ADDR_PCT_CD' (int)                Code of Precinct in which the Incident Occured
    'RPT_DT' (date)                    Report Date
    'KY_CD' (int)                      "Key Code": Offense Classification Code (3 digits)
    'OFNS_DESC' (str)                  Offense Description
    'PD_CD' (int)                      PD Code of Offense. More granular than Key Code
    'PD_DESC' (str)                    PD Description of Offense.
    'CRM_ATPT_CPTD_CD' (str)           Whether Crime was Atempted or Completed (values: 'COMPLETED', 'ATTEMPTED')
    'LAW_CAT_CD' (str)                 Level of Offense (values: 'FELONY', 'VIOLATION', 'MISDEMEANOR')
    'BORO_NM' (str)                    Name of Borough in which Incident Occurred
    'LOC_OF_OCCUR_DESC' (str)          Description of where the incident occurred with respect to the premises
                                       (values:'FRONT OF', 'REAR OF', 'OUTSIDE', 'INSIDE', 'OPPOSITE OF')
    'PREM_TYP_DESC' (str)              Description of the type of premises in which the Incident Occurred
    'JURIS_DESC' (str)                 Description of Jurisdiction in which Incident Occurred
    'JURISDICTION_CODE' (int)          Jurisdiction Code
    'PARKS_NM' (str)                   Name of Park in which Incident Occurred, if Applicable
    'HADEVELOPT' (str)                 Name of NYCHA Housing Development in which Incident Occurred, if Applicable
    'HOUSING_PSA' (int)                Housing PSA
    'X_COORD_CD' (int)                 X-coordinate, New York State Plane Coordinate System
    'Y_COORD_CD' (int)                 Y-coordinate, New York State Plane Coordinate System
    'SUSP_AGE_GROUP' (int)             Age Group of Suspect
    'SUSP_RACE' (str)                  Race of Suspect
    'SUSP_SEX' (str)                   Sex of Suspect
    'TRANSIT_DISTRICT' (int)           Transit-District code
    'Latitude' (float)                 Global Latitude of Location where Incident Occurred
    'Longitude' (float)                Global Longitude of Location where Incident Occured
    'Lat_Lon' (str)                    'Latitude' and 'Longitude' together
    'PATROL_BORO' (str)                Patrol Borough
    'STATION_NAME' (str)               Station Name
    'VIC_AGE_GROUP' (int)              Age Group of Victim
    'VIC_RACE' (str)                   Race of Victim
    'VIC_SEX' (str)                    Sex of Victim
    
    
    (Note: some field descriptions were taken from https://www1.nyc.gov/assets/nypd/downloads/pdf/analysis_and_planning/incident_level_data_footnotes.pdf)

## Profiling & Cleaning of each field in the data set

In [33]:
profiles.minmax('Full Complaint ID')

                 min              max
int  201900112120417  202112312274817

In [34]:
profiles.minmax('Complaint Year Number')

      min   max
int  2019  2021

In [35]:
profiles.minmax('Complaint Precinct Code')

     min  max
int    1  123

In [36]:
profiles.column('Complaint Precinct Code').get('topValues')

[('14', 43),
 ('90', 40),
 ('66', 37),
 ('13', 35),
 ('70', 33),
 ('18', 33),
 ('19', 32),
 ('71', 30),
 ('61', 28),
 ('1', 28)]

In [37]:
profiles.column('Law Code Category Description').get('topValues')

[('MISDEMEANOR', 606),
 ('FELONY', 559),
 ('VIOLATION', 15),
 ('INVESTIGATION', 1)]

In [38]:
ds_full.distinct('Law Code Category Description')

Counter({'FELONY': 559,
         'MISDEMEANOR': 606,
         'VIOLATION': 15,
         'INVESTIGATION': 1})

In [39]:
# Print the most frequent values in column 'PD_DESC'

profiles.column('PD Code Description').get('topValues')

[('AGGRAVATED HARASSMENT 1', 282),
 ('CRIMINAL MISCHIEF 4TH, GRAFFIT', 193),
 ('ASSAULT 3', 161),
 ('AGGRAVATED HARASSMENT 2', 152),
 ('ASSAULT 2,1,UNCLASSIFIED', 135),
 ('MENACING,UNCLASSIFIED', 39),
 ('MISCHIEF,CRIMINAL,    UNCL 2ND', 34),
 ('CRIMINAL MISCHIEF,UNCLASSIFIED 4', 34),
 ('CRIMINAL MIS 2 & 3', 22),
 ('ROBBERY,OPEN AREA UNCLASSIFIED', 12)]

In [40]:
ds_full.distinct('PD Code Description')

Counter({'ASSAULT 2,1,UNCLASSIFIED': 135,
         'ASSAULT 3': 161,
         'ROBBERY,POCKETBOOK/CARRIED BAG': 5,
         'RAPE 1': 1,
         'MENACING,UNCLASSIFIED': 39,
         'AGGRAVATED HARASSMENT 1': 282,
         'ROBBERY,OPEN AREA UNCLASSIFIED': 12,
         'AGGRAVATED HARASSMENT 2': 152,
         'MISCHIEF,CRIMINAL,    UNCL 2ND': 34,
         'BURGLARY,UNCLASSIFIED,NIGHT': 5,
         'MISCHIEF, CRIMINAL 4, OF MOTOR': 11,
         'CRIMINAL MISCHIEF,UNCLASSIFIED 4': 34,
         'TRESPASS 3, CRIMINAL': 1,
         'MURDER,UNCLASSIFIED': 1,
         'CRIMINAL MISCHIEF 4TH, GRAFFIT': 193,
         'WEAPONS POSSESSION 3': 1,
         'LARCENY,GRAND FROM PERSON,PERSONAL ELECTRONIC DEVICE(SNATCH)': 4,
         'CRIMINAL MIS 2 & 3': 22,
         'ROBBERY,CAR JACKING': 1,
         'ROBBERY,DWELLING': 2,
         'MISCHIEF, CRIMINAL 3 & 2, OF M': 9,
         'ROBBERY,PERSONAL ELECTRONIC DEVICE': 8,
         'LARCENY,GRAND FROM PERSON,UNCL': 10,
         'ROBBERY,COMMERCIAL UNCLASSIFIED': 2,
         'OBSTR BREATH/CIRCUL': 4,
         'ROBBERY,BEGIN AS SHOPLIFTING': 2,
         'MISCHIEF, CRIMINAL 4, BY FIRE': 6,
         'MENACING 1ST DEGREE (VICT NOT': 1,
         'ROBBERY,PUBLIC PLACE INSIDE': 2,
         'SEXUAL ABUSE': 1,
         'LARCENY,GRAND BY EXTORTION': 1,
         'HARASSMENT,SUBD 1,CIVILIAN': 4,
         'STRANGULATION 1ST': 1,
         'LARCENY,GRAND BY FALSE PROMISE-IN PERSON CONTACT': 1,
         'MANSLAUGHTER,UNCLASSIFIED - NO': 1,
         'HARASSMENT,SUBD 3,4,5': 11,
         'ROBBERY,RESIDENTIAL COMMON AREA': 1,
         'ROBBERY,NECKCHAIN/JEWELRY': 1,
         'INVESTIGATE CHILD ABUSE': 1,
         'BURGLARY,TRUCK NIGHT': 1,
         'MISCHIEF, CRIMINAL 3&2, BY FIR': 1,
         'FRAUD,UNCLASSIFIED-MISDEMEANOR': 1,
         'LARCENY,PETIT FROM BUILDING,UN': 1,
         'MAKING TERRORISTIC THREAT': 8,
         'LARCENY,PETIT FROM BUILDING,UNATTENDED, PACKAGE THEFT INSIDE': 1,
         'CHILD, ENDANGERING WELFARE': 1,
         'SEXUAL ABUSE 3,2': 1,
         'RECKLESS ENDANGERMENT 1': 1,
         'LARCENY,GRAND FROM RESIDENCE, UNATTENDED': 1,
         'ROBBERY,CLOTHING': 1})

In [41]:
profiles.column('Offense Description').get('topValues')

[('CRIMINAL MISCHIEF & RELATED OF', 310),
 ('MISCELLANEOUS PENAL LAW', 292),
 ('ASSAULT 3 & RELATED OFFENSES', 204),
 ('OFF. AGNST PUB ORD SENSBLTY &', 152),
 ('FELONY ASSAULT', 136),
 ('ROBBERY', 37),
 ('GRAND LARCENY', 17),
 ('HARRASSMENT 2', 15),
 ('BURGLARY', 6),
 ('SEX CRIMES', 3)]

In [42]:
ds_full.distinct('Offense Description')

Counter({'FELONY ASSAULT': 136,
         'ASSAULT 3 & RELATED OFFENSES': 204,
         'ROBBERY': 37,
         'RAPE': 1,
         'MISCELLANEOUS PENAL LAW': 292,
         'OFF. AGNST PUB ORD SENSBLTY &': 152,
         'CRIMINAL MISCHIEF & RELATED OF': 310,
         'BURGLARY': 6,
         'CRIMINAL TRESPASS': 1,
         'MURDER & NON-NEGL. MANSLAUGHTE': 2,
         'DANGEROUS WEAPONS': 1,
         'GRAND LARCENY': 17,
         'SEX CRIMES': 3,
         'HARRASSMENT 2': 15,
         'INVESTIGATIONS/COMPLAINTS ONLY': 1,
         'FRAUDS': 1,
         'PETIT LARCENY': 2})

In [43]:
ds_full.distinct('Offense Category')

Counter({'Sexual Orientation': 166,
         'Race/Color': 321,
         'Religion/Religious Practice': 596,
         'Ethnicity/National Origin/Ancestry': 40,
         'Gender': 50,
         'Unclassified': 6,
         'Age': 1,
         'Disability': 1})

In [46]:
ds_full.distinct('Patrol Borough Name')

Counter({'PATROL BORO BRONX': 95,
         'PATROL BORO BKLYN SOUTH': 218,
         'PATROL BORO BKLYN NORTH': 185,
         'PATROL BORO MAN NORTH': 160,
         'PATROL BORO MAN SOUTH': 261,
         'PATROL BORO QUEENS NORTH': 146,
         'PATROL BORO QUEENS SOUTH': 69,
         'PATROL BORO STATEN ISLAND': 47})

In [45]:
def validate_boro_nm(sourceValue):
    UNKNOWN = "UNKNOWN"
    
    try:
        values = ["PATROL BORO BRONX","PATROL BORO BKLYN SOUTH","PATROL BORO BKLYN NORTH","PATROL BORO MAN NORTH","PATROL BORO MAN SOUTH","PATROL BORO QUEENS NORTH","PATROL BORO QUEENS SOUTH","PATROL BORO STATEN ISLAND"]
        
        if sourceValue in values:
            return sourceValue
        else:
            return UNKNOWN
    except:
        return UNKNOWN

    
ds_full = ds_full.update('Patrol Borough Name', validate_boro_nm)

In [48]:
ds_full.distinct('County')

Counter({'BRONX': 95,
         'KINGS': 403,
         'NEW YORK': 421,
         'QUEENS': 215,
         'RICHMOND': 47})

In [49]:
profiles.column('Bias Motive Description').get('topValues')

[('ANTI-JEWISH', 536),
 ('ANTI-ASIAN', 164),
 ('ANTI-MALE HOMOSEXUAL (GAY)', 142),
 ('ANTI-BLACK', 108),
 ('ANTI-WHITE', 49),
 ('ANTI-TRANSGENDER', 30),
 ('ANTI-MUSLIM', 29),
 ('ANTI-CATHOLIC', 24),
 ('ANTI-OTHER ETHNICITY', 18),
 ('ANTI-HISPANIC', 15)]

In [50]:
ds_full.distinct('Bias Motive Description')

Counter({'ANTI-MALE HOMOSEXUAL (GAY)': 142,
         'ANTI-WHITE': 49,
         'ANTI-MUSLIM': 29,
         'ANTI-HISPANIC': 15,
         'ANTI-TRANSGENDER': 30,
         'ANTI-JEWISH': 536,
         'ANTI-ASIAN': 164,
         'ANTI-BLACK': 108,
         'ANTI-FEMALE HOMOSEXUAL (LESBIAN)': 14,
         'ANTI-ARAB': 7,
         'ANTI-CATHOLIC': 24,
         'ANTI-GENDER NON-CONFORMING': 6,
         'ANTI-FEMALE': 14,
         'ANTI-LGBT (MIXED GROUP)': 11,
         'ANTI-MULTI-RACIAL GROUPS': 3,
         'ANTI-OTHER ETHNICITY': 18,
         '60 YRS AND OLDER': 1,
         'ANTI-HINDU': 2,
         'ANTI-BUDDHIST': 2,
         'ANTI-JEHOVAHS WITNESS': 1,
         'ANTI-PHYSICAL DISABILITY': 1,
         'ANTI-OTHER RELIGION': 2,
         'ANTI-RELIGIOUS PRACTICE GENERALLY': 2})

In [53]:
profiles.column('Arrest Id').get('topValues')

[('B31682806', 2),
 ('B31678218', 1),
 ('B31682790', 1),
 ('B31692174', 1),
 ('B31692175', 1),
 ('B31692176', 1),
 ('B31697030', 1),
 ('B31702150', 1),
 ('B31704341', 1),
 ('B31714935', 1)]

In [54]:
ds_full.distinct('Arrest Id')

Counter({'B31678218': 1,
         'B31682790': 1,
         'B31682806': 2,
         'B31692174': 1,
         'B31692175': 1,
         'B31692176': 1,
         'B31697030': 1,
         'B31702150': 1,
         'B31704341': 1,
         'B31714935': 1,
         'B31714939': 1,
         'B31722870': 1,
         'B32676594': 1,
         'B32682489': 1,
         'B32682490': 1,
         'B32682492': 1,
         'B32684534': 1,
         'B32690509': 1,
         'B32690513': 1,
         'B32692369': 1,
         'B32698112': 1,
         'B32700799': 1,
         'B32701468': 1,
         'B33672940': 1,
         'B33678693': 1,
         'B33679800': 1,
         'B33682164': 1,
         'B33683675': 1,
         'B33683676': 1,
         'B33683677': 1,
         'B33683679': 1,
         'B33683680': 1,
         'B33683681': 1,
         'B33683682': 1,
         'B33683684': 1,
         'B33683686': 1,
         'B33683687': 1,
         'B33683688': 1,
         'B33683690': 1,
         'B33683691': 1,
         'B33695947': 1,
         'K31673178': 1,
         'K31674720': 1,
         'K31675023': 1,
         'K31677618': 1,
         'K31677619': 1,
         'K31677806': 1,
         'K31679592': 1,
         'K31682839': 1,
         'K31685143': 1,
         'K31688657': 1,
         'K31689355': 1,
         'K31689358': 1,
         'K31690178': 1,
         'K31690179': 1,
         'K31690180': 1,
         'K31690185': 1,
         'K31690190': 1,
         'K31690422': 1,
         'K31690691': 1,
         'K31697392': 1,
         'K31697975': 1,
         'K31701421': 1,
         'K31702285': 1,
         'K31702902': 1,
         'K31703750': 1,
         'K31703762': 1,
         'K31704373': 1,
         'K31704696': 1,
         'K31708016': 1,
         'K31708045': 1,
         'K31709845': 1,
         'K31710378': 1,
         'K31710427': 1,
         'K31710604': 1,
         'K31710607': 1,
         'K31712760': 1,
         'K31714905': 1,
         'K31716057': 1,
         'K31718271': 1,
         'K31718849': 1,
         'K31719978': 1,
         'K31724759': 1,
         'K31726204': 1,
         'K31726701': 1,
         'K31727109': 1,
         'K31728360': 1,
         'K31728363': 1,
         'K31730066': 1,
         'K31730069': 1,
         'K31730109': 1,
         'K31732764': 1,
         'K31734302': 1,
         'K31734384': 1,
         'K31734386': 1,
         'K31734389': 1,
         'K32672193': 1,
         'K32675055': 1,
         'K32676408': 1,
         'K32678354': 1,
         'K32682298': 1,
         'K32684172': 1,
         'K32684518': 1,
         'K32688722': 1,
         'K32688732': 1,
         'K32688835': 1,
         'K32688843': 1,
         'K32688863': 1,
         'K32688936': 1,
         'K32688942': 1,
         'K32688958': 1,
         'K32688959': 1,
         'K32689418': 1,
         'K32691655': 1,
         'K32692289': 1,
         'K32693334': 1,
         'K32696544': 1,
         'K32697729': 1,
         'K32702669': 1,
         'K32708126': 1,
         'K32709542': 1,
         'K32713232': 1,
         'K32713233': 1,
         'K32713235': 1,
         'K32713237': 1,
         'K32713374': 1,
         'K32713376': 1,
         'K32713379': 1,
         'K32713380': 1,
         'K33672671': 1,
         'K33672672': 1,
         'K33672673': 1,
         'K33672675': 1,
         'K33672676': 1,
         'K33672679': 1,
         'K33672681': 1,
         'K33672682': 1,
         'K33672683': 1,
         'K33677358': 1,
         'K33680922': 1,
         'K33681624': 1,
         'K33682979': 1,
         'K33684477': 1,
         'K33684480': 1,
         'K33684481': 1,
         'K33688246': 1,
         'K33689291': 1,
         'K33689292': 1,
         'K33689703': 1,
         'K33689742': 1,
         'K33689743': 1,
         'K33689745': 1,
         'K33689897': 1,
         'K33689898': 1,
         'K33689900': 1,
         'K33689901': 1,
         'K33689902': 1,
         'K33689903': 1,
         'K33691802': 1,
         'K33691805': 1,
         'K33691875': 1,
         'K33692226': 1,
         'K33692743': 1,
         'K33694392': 1,
         'K33697817': 1,
         'K33698818': 1,
         'K33701672': 1,
         'K33702895': 1,
         'K33703368': 1,
         'K33703397': 1,
         'K33704128': 1,
         'K33704546': 1,
         'M31676859': 1,
         'M31678638': 1,
         'M31678640': 1,
         'M31679002': 1,
         'M31682108': 1,
         'M31684381': 1,
         'M31684401': 1,
         'M31687591': 1,
         'M31693499': 1,
         'M31696193': 1,
         'M31697999': 1,
         'M31698085': 1,
         'M31698659': 1,
         'M31701654': 1,
         'M31702799': 1,
         'M31702800': 1,
         'M31703822': 1,
         'M31704481': 1,
         'M31705246': 1,
         'M31709092': 1,
         'M31709102': 1,
         'M31710089': 1,
         'M31710090': 1,
         'M31710091': 1,
         'M31712034': 1,
         'M31712037': 1,
         'M31712039': 1,
         'M31712505': 1,
         'M31713881': 1,
         'M31719199': 1,
         'M31721185': 1,
         'M31721880': 1,
         'M31723428': 1,
         'M31727652': 1,
         'M32673717': 1,
         'M32674183': 1,
         'M32676128': 1,
         'M32677660': 1,
         'M32678261': 1,
         'M32678917': 1,
         'M32681914': 1,
         'M32682527': 1,
         'M32682532': 1,
         'M32682870': 1,
         'M32683869': 1,
         'M32684360': 1,
         'M32688260': 1,
         'M32690599': 1,
         'M32692250': 1,
         'M32694928': 1,
         'M32695257': 1,
         'M32697732': 1,
         'M32700595': 1,
         'M32704105': 1,
         'M32705066': 1,
         'M32705927': 1,
         'M32706808': 1,
         'M32706958': 1,
         'M33672323': 1,
         'M33673062': 1,
         'M33676050': 1,
         'M33676236': 1,
         'M33677656': 1,
         'M33677739': 1,
         'M33678144': 1,
         'M33680683': 1,
         'M33680688': 1,
         'M33680785': 1,
         'M33681055': 1,
         'M33681143': 1,
         'M33681149': 1,
         'M33681338': 1,
         'M33681677': 1,
         'M33681763': 1,
         'M33682038': 1,
         'M33682684': 1,
         'M33682808': 1,
         'M33683046': 1,
         'M33683594': 1,
         'M33683716': 1,
         'M33684092': 1,
         'M33684637': 1,
         'M33684643': 1,
         'M33685070': 1,
         'M33685269': 1,
         'M33686788': 1,
         'M33687077': 1,
         'M33687220': 1,
         'M33687504': 1,
         'M33687797': 1,
         'M33687850': 1,
         'M33688566': 1,
         'M33688681': 1,
         'M33688716': 1,
         'M33688899': 1,
         'M33689084': 1,
         'M33689226': 1,
         'M33689227': 1,
         'M33690462': 1,
         'M33690675': 1,
         'M33690688': 1,
         'M33690904': 1,
         'M33690930': 1,
         'M33691019': 1,
         'M33691116': 1,
         'M33692323': 1,
         'M33692324': 1,
         'M33692326': 1,
         'M33692808': 1,
         'M33693696': 1,
         'M33694095': 1,
         'M33694195': 1,
         'M33694197': 1,
         'M33694199': 1,
         'M33694200': 1,
         'M33694236': 1,
         'M33694550': 1,
         'M33694630': 1,
         'M33696391': 1,
         'M33697103': 1,
         'M33697151': 1,
         'M33698089': 1,
         'M33698336': 1,
         'M33698436': 1,
         'M33698488': 1,
         'M33699519': 1,
         'M33700248': 1,
         'M33700494': 1,
         'M33701548': 1,
         'M33701797': 1,
         'M33701825': 1,
         'M33702584': 1,
         'Q31679178': 1,
         'Q31679685': 1,
         'Q31679958': 1,
         'Q31680459': 1,
         'Q31684836': 1,
         'Q31685005': 1,
         'Q31685303': 1,
         'Q31687940': 1,
         'Q31688353': 1,
         'Q31690349': 1,
         'Q31696251': 1,
         'Q31696472': 1,
         'Q31699814': 1,
         'Q31699816': 1,
         'Q31704457': 1,
         'Q31710151': 1,
         'Q31717201': 1,
         'Q31717202': 1,
         'Q32674324': 1,
         'Q32674328': 1,
         'Q32674331': 1,
         'Q32674334': 1,
         'Q32676547': 1,
         'Q32680497': 1,
         'Q32685894': 1,
         'Q32686914': 1,
         'Q32686988': 1,
         'Q32687409': 1,
         'Q32688927': 1,
         'Q32693311': 1,
         'Q32694547': 1,
         'Q32694806': 1,
         'Q32695451': 1,
         'Q32696681': 1,
         'Q32696686': 1,
         'Q32696687': 1,
         'Q32696688': 1,
         'Q32699240': 1,
         'Q33678801': 1,
         'Q33678904': 1,
         'Q33678907': 1,
         'Q33678908': 1,
         'Q33680385': 1,
         'Q33681793': 1,
         'Q33682126': 1,
         'Q33682266': 1,
         'Q33682365': 1,
         'Q33682366': 1,
         'Q33682476': 1,
         'Q33684042': 1,
         'Q33685718': 1,
         'Q33686343': 1,
         'Q33686371': 1,
         'Q33686378': 1,
         'Q33687640': 1,
         'Q33687647': 1,
         'Q33688706': 1,
         'Q33688708': 1,
         'Q33688936': 1,
         'Q33690220': 1,
         'Q33691020': 1,
         'Q33691022': 1,
         'Q33691024': 1,
         'Q33691027': 1,
         'Q33691384': 1,
         'Q33691446': 1,
         'Q33691447': 1,
         'Q33691448': 1,
         'Q33691449': 1,
         'Q33692103': 1,
         'Q33695573': 1,
         'Q33695575': 1,
         'Q33695576': 1,
         'Q33695904': 1,
         'Q33697244': 1,
         'S32675770': 1,
         'S32675771': 1,
         'S32675772': 1,
         'S32675773': 1,
         'S32675775': 1,
         'S33673857': 1,
         'S33673858': 1,
         'S33673859': 1,
         'S33673860': 1,
         'S33673861': 1,
         'S33673862': 1,
         'S33673863': 1,
         'S33675609': 1,
         'S33675709': 1,
         'S33675710': 1,
         'S33675711': 1,
         'S33675929': 1,
         '': 784})

In [55]:
SELECTED_COLUMNS = [\
    'Full Complaint ID',\
    'Complaint Year Number',\
    'Month Number',\
    'Record Create Date',\
    'Complaint Precinct Code',\
    'Patrol Borough Name',\
    'County',\
    'Law Code Category Description',\
    'Offense Description',\
    'PD Code Description',\
    'Bias Motive Description',\
    'Offense Category',\
    'Arrest Date',\
    'Arrest Id',\
]


ds_full = ds_full.select(SELECTED_COLUMNS)

In [56]:
ds_full

# VALIDATING DATA AFTER CLEANING

In [57]:
data_df = pd.read_csv("NYPD-Hate-Crimes.csv")

In [58]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1181 entries, 0 to 1180
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Full Complaint ID              1181 non-null   int64
 1   Complaint Year Number          1181 non-null   int64
 2   Month Number                   1181 non-null   int64
 3   Record Create Date             1181 non-null   object
 4   Complaint Precinct Code        1181 non-null   int64
 5   Patrol Borough Name            1181 non-null   object
 6   County                         1181 non-null   object
 7   Law Code Category Description  1181 non-null   object
 8   Offense Description            1181 non-null   object
 9   PD Code Description            1181 non-null   object
 10  Bias Motive Description        1181 non-null   object
 11  Offense Category               1181 non-null   object
 12  Arrest Date                    397 non-null    object
 13  Arrest Id                      397 non-null    object
dtypes: int64(4), object(10)
memory usage: 129.3+ KB

In [59]:
ds_full_jc = stream(data_df)
profiles = ds_full_jc.profile(default_profiler=DefaultColumnProfiler)
profiles.stats()

                               total  empty  distinct  uniqueness    entropy
Full Complaint ID               1181      0      1102    0.933108  10.055231
Complaint Year Number           1181      0         3    0.002540   1.555348
Month Number                    1181      0        12    0.010161   3.529311
Record Create Date              1181      0       609    0.515665   8.973195
Complaint Precinct Code         1181      0        76    0.064352   5.960441
Patrol Borough Name             1181      0         8    0.006774   2.830716
County                          1181      0         5    0.004234   1.984774
Law Code Category Description   1181      0         4    0.003387   1.093351
Offense Description             1181      0        17    0.014395   2.641960
PD Code Description             1181      0        50    0.042337   3.476055
Bias Motive Description         1181      0        23    0.019475   2.745725
Offense Category                1181      0         8    0.006774   1.821166
Arrest Date                     1181    784       237    0.596977   7.547864
Arrest Id                       1181    784       396    0.997481   8.627957

In [60]:
data_df['Arrest Date'].unique()

array(['02/08/2019', '03/09/2019', '05/10/2019', '06/14/2019',
       '07/21/2019', '08/05/2019', '10/22/2019', '12/28/2019',
       '02/06/2020', '03/28/2020', '04/29/2020', '07/07/2020',
       '08/06/2020', '10/08/2020', '11/03/2020', '11/10/2020',
       '01/08/2021', '03/04/2021', '03/14/2021', '04/09/2021',
       '05/01/2021', '09/06/2021', '01/06/2019', '01/14/2019',
       '01/16/2019', '01/30/2019', '02/27/2019', '03/11/2019',
       '03/29/2019', '04/02/2019', '04/06/2019', '04/05/2019',
       '04/07/2019', '04/08/2019', '05/15/2019', '05/17/2019',
       '06/06/2019', '06/11/2019', '06/19/2019', '06/22/2019',
       '06/25/2019', '07/13/2019', '07/24/2019', '07/26/2019',
       '07/28/2019', '08/09/2019', '08/21/2019', '08/29/2019',
       '09/12/2019', '09/15/2019', '09/22/2019', '10/21/2019',
       '10/30/2019', '11/03/2019', '11/05/2019', '11/13/2019',
       '11/23/2019', '12/13/2019', '12/26/2019', '12/27/2019',
       '01/01/2020', '01/21/2020', '01/29/2020', '02/11/2020',
       '03/06/2020', '03/19/2020', '03/24/2020', '05/10/2020',
       '05/12/2020', '05/15/2020', '06/01/2020', '06/11/2020',
       '06/27/2020', '08/09/2020', '08/21/2020', '10/04/2020',
       '11/17/2020', '11/28/2020', '12/30/2020', '12/31/2020',
       '01/05/2021', '02/10/2021', '03/09/2021', '03/13/2021',
       '03/23/2021', '04/07/2021', '05/13/2021', '05/21/2021',
       '05/24/2021', '05/25/2021', '05/26/2021', '06/10/2021',
       '06/11/2021', '06/14/2021', '06/18/2021', '07/02/2021',
       '07/29/2021', '08/06/2021', '08/28/2021', '09/08/2021',
       '09/11/2021', '09/12/2021', '09/17/2021', '09/21/2021',
       '01/29/2019', '02/09/2019', '02/11/2019', '03/02/2019',
       '03/17/2019', '05/28/2019', '06/07/2019', '06/08/2019',
       '06/12/2019', '07/02/2019', '07/09/2019', '07/15/2019',
       '07/19/2019', '08/16/2019', '08/23/2019', '09/05/2019',
       '09/09/2019', '09/18/2019', '10/23/2019', '11/06/2019',
       '11/11/2019', '11/21/2019', '12/23/2019', '01/14/2020',
       '01/16/2020', '01/30/2020', '02/10/2020', '02/14/2020',
       '02/19/2020', '03/10/2020', '03/13/2020', '03/16/2020',
       '03/29/2020', '04/08/2020', '05/24/2020', '06/12/2020',
       '07/16/2020', '08/25/2020', '08/30/2020', '09/27/2020',
       '10/24/2020', '11/30/2020', '12/08/2020', '12/15/2020',
       '12/26/2020', '12/28/2020', '01/04/2021', '01/11/2021',
       '02/07/2021', '02/09/2021', '02/22/2021', '02/23/2021',
       '02/25/2021', '03/18/2021', '03/19/2021', '03/21/2021',
       '03/22/2021', '03/24/2021', '03/26/2021', '03/27/2021',
       '03/31/2021', '04/06/2021', '04/14/2021', '04/15/2021',
       '04/20/2021', '04/27/2021', '05/04/2021', '05/18/2021',
       '05/20/2021', '05/27/2021', '06/03/2021', '06/04/2021',
       '06/06/2021', '06/08/2021', '06/09/2021', '06/21/2021',
       '06/23/2021', '06/24/2021', '07/07/2021', '07/11/2021',
       '07/19/2021', '07/22/2021', '07/23/2021', '07/26/2021',
       '07/27/2021', '08/11/2021', '08/16/2021', '08/17/2021',
       '08/24/2021', '08/26/2021', '08/27/2021', '09/05/2021',
       '09/13/2021', '09/23/2021', '09/29/2021', '02/23/2019',
       '03/01/2019', '03/05/2019', '04/04/2019', '04/25/2019',
       '04/29/2019', '05/14/2019', '06/27/2019', '06/29/2019',
       '07/23/2019', '08/28/2019', '10/15/2019', '12/16/2019',
       '01/22/2020', '03/14/2020', '06/05/2020', '06/06/2020',
       '09/07/2020', '09/21/2020', '09/24/2020', '10/01/2020',
       '10/14/2020', '11/12/2020', '03/12/2021', '04/12/2021',
       '04/17/2021', '04/19/2021', '05/10/2021', '05/28/2021',
       '06/17/2021', '06/29/2021', '07/01/2021', '07/15/2021',
       '08/03/2021', '09/07/2021', '09/10/2021', '06/30/2021',
       '07/09/2021', nan], dtype=object)

In [61]:
def validate_Arrest_Date(data,column_name):
    data[column_name].replace(np.nan, 'UNKNOWN', inplace=True)
    return data
data_df = validate_Arrest_Date(data_df,'Arrest Date')

In [62]:
data_df['Arrest Id'].unique()

array(['B31678218', 'B31682790', 'B31682806', 'B31692174', 'B31692175',
       'B31692176', 'B31697030', 'B31702150', 'B31704341', 'B31714935',
       'B31714939', 'B31722870', 'B32676594', 'B32682489', 'B32682490',
       'B32682492', 'B32684534', 'B32690509', 'B32690513', 'B32692369',
       'B32698112', 'B32700799', 'B32701468', 'B33672940', 'B33678693',
       'B33679800', 'B33682164', 'B33683675', 'B33683676', 'B33683677',
       'B33683679', 'B33683680', 'B33683681', 'B33683682', 'B33683684',
       'B33683686', 'B33683687', 'B33683688', 'B33683690', 'B33683691',
       'B33695947', 'K31673178', 'K31674720', 'K31675023', 'K31677618',
       'K31677619', 'K31677806', 'K31679592', 'K31682839', 'K31685143',
       'K31688657', 'K31689355', 'K31689358', 'K31690178', 'K31690179',
       'K31690180', 'K31690185', 'K31690190', 'K31690422', 'K31690691',
       'K31697392', 'K31697975', 'K31701421', 'K31702285', 'K31702902',
       'K31703750', 'K31703762', 'K31704373', 'K31704696', 'K31708016',
       'K31708045', 'K31709845', 'K31710378', 'K31710427', 'K31710604',
       'K31710607', 'K31712760', 'K31714905', 'K31716057', 'K31718271',
       'K31718849', 'K31719978', 'K31724759', 'K31726204', 'K31726701',
       'K31727109', 'K31728360', 'K31728363', 'K31730066', 'K31730069',
       'K31730109', 'K31732764', 'K31734302', 'K31734384', 'K31734386',
       'K31734389', 'K32672193', 'K32675055', 'K32676408', 'K32678354',
       'K32682298', 'K32684172', 'K32684518', 'K32688722', 'K32688732',
       'K32688835', 'K32688843', 'K32688863', 'K32688936', 'K32688942',
       'K32688958', 'K32688959', 'K32689418', 'K32691655', 'K32692289',
       'K32693334', 'K32696544', 'K32697729', 'K32702669', 'K32708126',
       'K32709542', 'K32713232', 'K32713233', 'K32713235', 'K32713237',
       'K32713374', 'K32713376', 'K32713379', 'K32713380', 'K33672671',
       'K33672672', 'K33672673', 'K33672675', 'K33672676', 'K33672679',
       'K33672681', 'K33672682', 'K33672683', 'K33677358', 'K33680922',
       'K33681624', 'K33682979', 'K33684477', 'K33684480', 'K33684481',
       'K33688246', 'K33689291', 'K33689292', 'K33689703', 'K33689742',
       'K33689743', 'K33689745', 'K33689897', 'K33689898', 'K33689900',
       'K33689901', 'K33689902', 'K33689903', 'K33691802', 'K33691805',
       'K33691875', 'K33692226', 'K33692743', 'K33694392', 'K33697817',
       'K33698818', 'K33701672', 'K33702895', 'K33703368', 'K33703397',
       'K33704128', 'K33704546', 'M31676859', 'M31678638', 'M31678640',
       'M31679002', 'M31682108', 'M31684381', 'M31684401', 'M31687591',
       'M31693499', 'M31696193', 'M31697999', 'M31698085', 'M31698659',
       'M31701654', 'M31702799', 'M31702800', 'M31703822', 'M31704481',
       'M31705246', 'M31709092', 'M31709102', 'M31710089', 'M31710090',
       'M31710091', 'M31712034', 'M31712037', 'M31712039', 'M31712505',
       'M31713881', 'M31719199', 'M31721185', 'M31721880', 'M31723428',
       'M31727652', 'M32673717', 'M32674183', 'M32676128', 'M32677660',
       'M32678261', 'M32678917', 'M32681914', 'M32682527', 'M32682532',
       'M32682870', 'M32683869', 'M32684360', 'M32688260', 'M32690599',
       'M32692250', 'M32694928', 'M32695257', 'M32697732', 'M32700595',
       'M32704105', 'M32705066', 'M32705927', 'M32706808', 'M32706958',
       'M33672323', 'M33673062', 'M33676050', 'M33676236', 'M33677656',
       'M33677739', 'M33678144', 'M33680683', 'M33680688', 'M33680785',
       'M33681055', 'M33681143', 'M33681149', 'M33681338', 'M33681677',
       'M33681763', 'M33682038', 'M33682684', 'M33682808', 'M33683046',
       'M33683594', 'M33683716', 'M33684092', 'M33684637', 'M33684643',
       'M33685070', 'M33685269', 'M33686788', 'M33687077', 'M33687220',
       'M33687504', 'M33687797', 'M33687850', 'M33688566', 'M33688681',
       'M33688716', 'M33688899', 'M33689084', 'M33689226', 'M33689227',
       'M33690462', 'M33690675', 'M33690688', 'M33690904', 'M33690930',
       'M33691019', 'M33691116', 'M33692323', 'M33692324', 'M33692326',
       'M33692808', 'M33693696', 'M33694095', 'M33694195', 'M33694197',
       'M33694199', 'M33694200', 'M33694236', 'M33694550', 'M33694630',
       'M33696391', 'M33697103', 'M33697151', 'M33698089', 'M33698336',
       'M33698436', 'M33698488', 'M33699519', 'M33700248', 'M33700494',
       'M33701548', 'M33701797', 'M33701825', 'M33702584', 'Q31679178',
       'Q31679685', 'Q31679958', 'Q31680459', 'Q31684836', 'Q31685005',
       'Q31685303', 'Q31687940', 'Q31688353', 'Q31690349', 'Q31696251',
       'Q31696472', 'Q31699814', 'Q31699816', 'Q31704457', 'Q31710151',
       'Q31717201', 'Q31717202', 'Q32674324', 'Q32674328', 'Q32674331',
       'Q32674334', 'Q32676547', 'Q32680497', 'Q32685894', 'Q32686914',
       'Q32686988', 'Q32687409', 'Q32688927', 'Q32693311', 'Q32694547',
       'Q32694806', 'Q32695451', 'Q32696681', 'Q32696686', 'Q32696687',
       'Q32696688', 'Q32699240', 'Q33678801', 'Q33678904', 'Q33678907',
       'Q33678908', 'Q33680385', 'Q33681793', 'Q33682126', 'Q33682266',
       'Q33682365', 'Q33682366', 'Q33682476', 'Q33684042', 'Q33685718',
       'Q33686343', 'Q33686371', 'Q33686378', 'Q33687640', 'Q33687647',
       'Q33688706', 'Q33688708', 'Q33688936', 'Q33690220', 'Q33691020',
       'Q33691022', 'Q33691024', 'Q33691027', 'Q33691384', 'Q33691446',
       'Q33691447', 'Q33691448', 'Q33691449', 'Q33692103', 'Q33695573',
       'Q33695575', 'Q33695576', 'Q33695904', 'Q33697244', 'S32675770',
       'S32675771', 'S32675772', 'S32675773', 'S32675775', 'S33673857',
       'S33673858', 'S33673859', 'S33673860', 'S33673861', 'S33673862',
       'S33673863', 'S33675609', 'S33675709', 'S33675710', 'S33675711',
       'S33675929', nan], dtype=object)

In [63]:
def validate_Arrest_id(data,column_name):
    data[column_name].replace(np.nan, 'UNKNOWN', inplace=True)
    return data
data_df = validate_Arrest_id(data_df,'Arrest Id')

In [64]:
ds_full_jc = stream(data_df)
profiles = ds_full_jc.profile(default_profiler=DefaultColumnProfiler)
profiles.stats()

                               total  empty  distinct  uniqueness    entropy
Full Complaint ID               1181      0      1102    0.933108  10.055231
Complaint Year Number           1181      0         3    0.002540   1.555348
Month Number                    1181      0        12    0.010161   3.529311
Record Create Date              1181      0       609    0.515665   8.973195
Complaint Precinct Code         1181      0        76    0.064352   5.960441
Patrol Borough Name             1181      0         8    0.006774   2.830716
County                          1181      0         5    0.004234   1.984774
Law Code Category Description   1181      0         4    0.003387   1.093351
Offense Description             1181      0        17    0.014395   2.641960
PD Code Description             1181      0        50    0.042337   3.476055
Bias Motive Description         1181      0        23    0.019475   2.745725
Offense Category                1181      0         8    0.006774   1.821166
Arrest Date                     1181      0       238    0.201524   3.458351
Arrest Id                       1181      0       397    0.336156   3.821430

In [71]:
data_df = data_df.drop_duplicates(subset='Full Complaint ID')

In [72]:
ds_full_jc = stream(data_df)
profiles = ds_full_jc.profile(default_profiler=DefaultColumnProfiler)
profiles.stats()

                               total  empty  distinct  uniqueness    entropy
Full Complaint ID               1102      0      1102    1.000000  10.105909
Complaint Year Number           1102      0         3    0.002722   1.554723
Month Number                    1102      0        12    0.010889   3.530658
Record Create Date              1102      0       609    0.552632   9.004818
Complaint Precinct Code         1102      0        76    0.068966   5.964229
Patrol Borough Name             1102      0         8    0.007260   2.830209
County                          1102      0         5    0.004537   1.981963
Law Code Category Description   1102      0         4    0.003630   1.096697
Offense Description             1102      0        17    0.015426   2.593761
PD Code Description             1102      0        50    0.045372   3.424492
Bias Motive Description         1102      0        23    0.020871   2.731725
Offense Category                1102      0         8    0.007260   1.809617
Arrest Date                     1102      0       228    0.206897   3.266991
Arrest Id                       1102      0       347    0.314882   3.554138

In [73]:
data_df.to_csv('filtered7.csv')