In [116]:
import sys #access to system parameters https://docs.python.org/3/library/sys.html
print("Python version: {}". format(sys.version))

import pandas as pd #collection of functions for data processing and analysis modeled after R dataframes with SQL like features
print("pandas version: {}". format(pd.__version__))

import matplotlib #collection of functions for scientific and publication-ready visualization
import matplotlib as plt
print("matplotlib version: {}". format(matplotlib.__version__))

import numpy as np #foundational package for scientific computing
print("NumPy version: {}". format(np.__version__))

import scipy as sp #collection of functions for scientific computing and advance mathematics
print("SciPy version: {}". format(sp.__version__)) 

import IPython
from IPython import display #pretty printing of dataframes in Jupyter notebook
print("IPython version: {}". format(IPython.__version__)) 

import sklearn #collection of machine learning algorithms
print("scikit-learn version: {}". format(sklearn.__version__))
from openclean.pipeline import stream
#misc libraries
import random
import time
#ignore warnings
import warnings
warnings.filterwarnings('ignore')
print('-'*25)
import re
import os
import matplotlib.pyplot as plt
%matplotlib inline

Python version: 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15)
[Clang 6.0 (clang-600.0.57)]
pandas version: 1.3.4
matplotlib version: 3.4.3
NumPy version: 1.21.3
SciPy version: 1.7.1
IPython version: 7.29.0
scikit-learn version: 1.0.1
-------------------------

In [2]:
#url = 'https://data.cityofnewyork.us/api/views/qgea-i56i/rows.csv?accessType=DOWNLOAD'
fn_src = 'https://data.cityofnewyork.us/api/views/uip8-fykc/rows.csv?accessType=DOWNLOAD'
fn_dst = 'NYPD_Arrest_Data.csv'

from six.moves import urllib

if os.path.isfile(fn_dst):
    print('File %s has already been downloaded' % fn_dst)
else:
    print('Fetching file %s[2.4GB]. This may take a while...' % fn_dst)
    urllib.request.urlretrieve(fn_src, fn_dst)
    print('File %s has been downloaded' % fn_dst)

Fetching file NYPD_Arrest_Data.csv[2.4GB]. This may take a while...
File NYPD_Arrest_Data.csv has been downloaded

### Open a stream

In [65]:
from openclean.pipeline import stream
ds_full = stream(fn_dst)

In [66]:
print(f'The dataset contains {ds_full.count():,} rows.')

The dataset contains 115,299 rows.

In [67]:
ds_full.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,09/29/2021,105,STRANGULATION 1ST,106,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.82618898100003,-73.90973778899996,POINT (-73.90973778899996 40.82618898100003)
1,234129823,09/27/2021,157,RAPE 1,104,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.67458330800008,-73.93022154099998,POINT (-73.93022154099998 40.67458330800008)
2,234040747,09/25/2021,109,"ASSAULT 2,1,UNCLASSIFIED",106,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.60344094100003,-73.76598558899997,POINT (-73.76598558899997 40.60344094100003)
3,234047720,09/25/2021,101,ASSAULT 3,344,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.83778161800007,-73.91945797099999,POINT (-73.91945797099999 40.83778161800007)
4,234042526,09/25/2021,101,ASSAULT 3,344,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.83598980000005,-73.91627635999998,POINT (-73.91627635999998 40.83598980000005)
5,234006839,09/24/2021,582,,,,PL 2225501,F,M,23,0,25-44,M,BLACK,998659,228177,40.79296572700008,-73.94796350499998,POINT (-73.94796350499998 40.79296572700008)
6,233952333,09/23/2021,397,"ROBBERY,OPEN AREA UNCLASSIFIED",105,ROBBERY,PL 1600500,F,K,75,0,18-24,M,BLACK,1017119,183909,40.67141166300007,-73.88151172399995,POINT (-73.88151172399995 40.67141166300007)
7,233878488,09/21/2021,105,STRANGULATION 1ST,106,FELONY ASSAULT,PL 1211300,F,B,40,0,25-44,M,WHITE,1010679,234533,40.81038342800008,-73.90452841699994,POINT (-73.90452841699994 40.81038342800008)
8,233784866,09/19/2021,101,ASSAULT 3,344,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,F,BLACK,1004489,237844,40.81948754300004,-73.926879392,POINT (-73.926879392 40.81948754300004)
9,233647454,09/16/2021,397,"ROBBERY,OPEN AREA UNCLASSIFIED",105,ROBBERY,PL 1601503,F,K,61,0,18-24,M,BLACK,995834,161062,40.60875497300003,-73.95828138999997,POINT (-73.95828138999997 40.60875497300003)

#### Use openclean to profile the data set:

In [68]:
from openclean.profiling.column import DefaultColumnProfiler

#profiles = ds.profile(default_profiler=DefaultColumnProfiler)
profiles = ds_full.profile(default_profiler=DefaultColumnProfiler)

In [69]:
profiles.stats()

                           total  empty  distinct  uniqueness    entropy
ARREST_KEY                115299      0    115299    1.000000  16.815020
ARREST_DATE               115299      0       273    0.002368   8.047698
PD_CD                     115299     21       252    0.002186   5.401154
PD_DESC                   115299     61       233    0.002022   5.366524
KY_CD                     115299     61        66    0.000573   4.534242
OFNS_DESC                 115299     61        63    0.000547   4.339051
LAW_CODE                  115299      0       922    0.007997   6.328932
LAW_CAT_CD                115299   1078         4    0.000035   1.032090
ARREST_BORO               115299      0         5    0.000043   2.172560
ARREST_PRECINCT           115299      0        77    0.000668   6.119069
JURISDICTION_CODE         115299      0        25    0.000217   0.618718
AGE_GROUP                 115299      0         5    0.000043   1.615421
PERP_SEX                  115299      0         2    0.000017   0.654703
PERP_RACE                 115299      0         7    0.000061   1.943492
X_COORD_CD                115299      0     23851    0.206862  12.430475
Y_COORD_CD                115299      0     25306    0.219482  12.501218
Latitude                  115299      0     28856    0.250271  12.637352
Longitude                 115299      0     28855    0.250262  12.637364
New Georeferenced Column  115299      0     28859    0.250297  12.637470

In [70]:
profiles.minmax('ARREST_KEY')

           min        max
int  222471128  234352983

In [71]:
ds_full.distinct('PD_CD')

Counter({'105': 2106,
         '157': 258,
         '109': 8591,
         '101': 14678,
         '582': 1,
         '397': 5678,
         '244': 3208,
         '166': 9,
         '153': 149,
         '263': 81,
         '748': 1815,
         '515': 937,
         '779': 5256,
         '681': 1351,
         '729': 2444,
         '293': 103,
         '155': 52,
         '177': 258,
         '339': 9110,
         '175': 716,
         '750': 879,
         '490': 534,
         '922': 3728,
         '511': 3197,
         '904': 275,
         '847': 558,
         '259': 2540,
         '113': 3296,
         '792': 3461,
         '705': 2956,
         '439': 4100,
         '782': 1320,
         '493': 150,
         '969': 1109,
         '509': 31,
         '639': 2165,
         '268': 2617,
         '129': 35,
         '802': 279,
         '117': 580,
         '548': 66,
         '503': 1852,
         '649': 67,
         '49': 974,
         '209': 292,
         '462': 350,
         '409': 56,
         '205': 339,
         '494': 674,
         '114': 1963,
         '258': 941,
         '106': 775,
         '759': 641,
         '115': 645,
         '203': 606,
         '513': 6,
         '269': 435,
         '475': 137,
         '441': 840,
         '419': 500,
         '478': 940,
         '301': 22,
         '199': 160,
         '940': 92,
         '112': 129,
         '793': 661,
         '139': 1122,
         '507': 153,
         '848': 406,
         '661': 188,
         '905': 1644,
         '': 21,
         '760': 178,
         '817': 56,
         '505': 113,
         '198': 440,
         '461': 210,
         '168': 94,
         '707': 209,
         '256': 21,
         '510': 305,
         '918': 58,
         '501': 158,
         '640': 70,
         '512': 54,
         '724': 164,
         '500': 296,
         '849': 110,
         '916': 209,
         '544': 146,
         '201': 15,
         '746': 82,
         '808': 44,
         '809': 34,
         '739': 127,
         '862': 35,
         '718': 29,
         '514': 64,
         '563': 66,
         '223': 299,
         '291': 43,
         '764': 58,
         '508': 261,
         '596': 36,
         '968': 17,
         '440': 92,
         '180': 46,
         '170': 24,
         '273': 376,
         '725': 40,
         '193': 10,
         '578': 16,
         '181': 84,
         '176': 11,
         '523': 65,
         '643': 22,
         '466': 25,
         '695': 25,
         '781': 12,
         '708': 18,
         '183': 34,
         '799': 24,
         '164': 28,
         '35': 1,
         '638': 22,
         '185': 15,
         '125': 20,
         '16': 97,
         '662': 95,
         '553': 23,
         '698': 11,
         '521': 23,
         '297': 55,
         '877': 13,
         '29': 4,
         '907': 67,
         '697': 9,
         '625': 27,
         '502': 49,
         '565': 37,
         '972': 1,
         '581': 3,
         '557': 9,
         '104': 37,
         '122': 6,
         '762': 6,
         '665': 42,
         '576': 24,
         '688': 17,
         '277': 14,
         '787': 1,
         '879': 7,
         '299': 6,
         '594': 14,
         '476': 3,
         '744': 44,
         '696': 24,
         '878': 7,
         '107': 6,
         '947': 3,
         '584': 2,
         '15': 2,
         '100': 2,
         '579': 13,
         '997': 2,
         '645': 13,
         '742': 6,
         '841': 6,
         '784': 4,
         '532': 3,
         '464': 4,
         '0': 2,
         '271': 11,
         '265': 24,
         '872': 2,
         '827': 14,
         '174': 1,
         '179': 9,
         '733': 2,
         '531': 11,
         '889': 1,
         '283': 1,
         '380': 27,
         '749': 1,
         '184': 1,
         '909': 3,
         '477': 2,
         '652': 6,
         '701': 4,
         '479': 28,
         '844': 8,
         '772': 3,
         '186': 9,
         '775': 19,
         '267': 10,
         '583': 1,
         '191': 4,
         '659': 4,
         '586': 19,
         '788': 43,
         '498': 1,
         '438': 4,
         '815': 1,
         '520': 9,
         '694': 2,
         '943': 1,
         '794': 1,
         '610': 4,
         '899': 1,
         '766': 3,
         '687': 5,
         '637': 11,
         '770': 1,
         '196': 1,
         '588': 6,
         '939': 3,
         '405': 8,
         '574': 6,
         '593': 1,
         '197': 16,
         '706': 6,
         '721': 1,
         '703': 1,
         '674': 1,
         '123': 1,
         '195': 4,
         '254': 5,
         '789': 6,
         '874': 3,
         '727': 3,
         '261': 5,
         '685': 2,
         '906': 9,
         '585': 3,
         '204': 2,
         '248': 1,
         '569': 274,
         '568': 153,
         '567': 134,
         '711': 1,
         '719': 4,
         '672': 8,
         '566': 29,
         '187': 3,
         '570': 15,
         '961': 1,
         '777': 1,
         '963': 2,
         '379': 1,
         '783': 1,
         '648': 2,
         '124': 1,
         '644': 1})

In [72]:
profiles.minmax('PD_CD')

     min  max
int    0  997

In [109]:
profiles.minmax('KY_CD')

     min  max
int  101  995

### Validating PD_CD Column by removing empty values

In [98]:
data_df = pd.read_csv("NYPD_Arrest_Data.csv")

In [101]:
def validate_PD(data,column_name):
    data = data[data[column_name].between(1,998)]
    return data

    
##ds_full = ds_full.update('PD_CD', validate_PD_CD)

In [102]:
## ds_full = ds_full.update('CRM_ATPT_CPTD_CD', validate_crime_indicator)
data_df = validate_PD(data_df,'PD_CD')
#column8[column8['VIC_AGE_GROUP'] == ""]
data_df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,09/29/2021,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,09/27/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,09/25/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,09/25/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,09/25/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,01/06/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,01/05/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,01/01/2021,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,B,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,01/07/2021,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,01/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,K,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

In [103]:
from openclean.pipeline import stream
ds_full1 = stream(data_df)
## ds_full.distinct('PD_CD')

In [104]:
ds_full1.distinct('PD_CD')

Counter({105.0: 2106,
         157.0: 258,
         109.0: 8591,
         101.0: 14678,
         582.0: 1,
         397.0: 5678,
         244.0: 3208,
         166.0: 9,
         153.0: 149,
         263.0: 81,
         748.0: 1815,
         515.0: 937,
         779.0: 5256,
         681.0: 1351,
         729.0: 2444,
         293.0: 103,
         155.0: 52,
         177.0: 258,
         339.0: 9110,
         175.0: 716,
         750.0: 879,
         490.0: 534,
         922.0: 3728,
         511.0: 3197,
         904.0: 275,
         847.0: 558,
         259.0: 2540,
         113.0: 3296,
         792.0: 3461,
         705.0: 2956,
         439.0: 4100,
         782.0: 1320,
         493.0: 150,
         969.0: 1109,
         509.0: 31,
         639.0: 2165,
         268.0: 2617,
         129.0: 35,
         802.0: 279,
         117.0: 580,
         548.0: 66,
         503.0: 1852,
         649.0: 67,
         49.0: 974,
         209.0: 292,
         462.0: 350,
         409.0: 56,
         205.0: 339,
         494.0: 674,
         114.0: 1963,
         258.0: 941,
         106.0: 775,
         759.0: 641,
         115.0: 645,
         203.0: 606,
         513.0: 6,
         269.0: 435,
         475.0: 137,
         441.0: 840,
         419.0: 500,
         478.0: 940,
         301.0: 22,
         199.0: 160,
         940.0: 92,
         112.0: 129,
         793.0: 661,
         139.0: 1122,
         507.0: 153,
         848.0: 406,
         661.0: 188,
         905.0: 1644,
         760.0: 178,
         817.0: 56,
         505.0: 113,
         198.0: 440,
         461.0: 210,
         168.0: 94,
         707.0: 209,
         256.0: 21,
         510.0: 305,
         918.0: 58,
         501.0: 158,
         640.0: 70,
         512.0: 54,
         724.0: 164,
         500.0: 296,
         849.0: 110,
         916.0: 209,
         544.0: 146,
         201.0: 15,
         746.0: 82,
         808.0: 44,
         809.0: 34,
         739.0: 127,
         862.0: 35,
         718.0: 29,
         514.0: 64,
         563.0: 66,
         223.0: 299,
         291.0: 43,
         764.0: 58,
         508.0: 261,
         596.0: 36,
         968.0: 17,
         440.0: 92,
         180.0: 46,
         170.0: 24,
         273.0: 376,
         725.0: 40,
         193.0: 10,
         578.0: 16,
         181.0: 84,
         176.0: 11,
         523.0: 65,
         643.0: 22,
         466.0: 25,
         695.0: 25,
         781.0: 12,
         708.0: 18,
         183.0: 34,
         799.0: 24,
         164.0: 28,
         35.0: 1,
         638.0: 22,
         185.0: 15,
         125.0: 20,
         16.0: 97,
         662.0: 95,
         553.0: 23,
         698.0: 11,
         521.0: 23,
         297.0: 55,
         877.0: 13,
         29.0: 4,
         907.0: 67,
         697.0: 9,
         625.0: 27,
         502.0: 49,
         565.0: 37,
         972.0: 1,
         581.0: 3,
         557.0: 9,
         104.0: 37,
         122.0: 6,
         762.0: 6,
         665.0: 42,
         576.0: 24,
         688.0: 17,
         277.0: 14,
         787.0: 1,
         879.0: 7,
         299.0: 6,
         594.0: 14,
         476.0: 3,
         744.0: 44,
         696.0: 24,
         878.0: 7,
         107.0: 6,
         947.0: 3,
         584.0: 2,
         15.0: 2,
         100.0: 2,
         579.0: 13,
         997.0: 2,
         645.0: 13,
         742.0: 6,
         841.0: 6,
         784.0: 4,
         532.0: 3,
         464.0: 4,
         271.0: 11,
         265.0: 24,
         872.0: 2,
         827.0: 14,
         174.0: 1,
         179.0: 9,
         733.0: 2,
         531.0: 11,
         889.0: 1,
         283.0: 1,
         380.0: 27,
         749.0: 1,
         184.0: 1,
         909.0: 3,
         477.0: 2,
         652.0: 6,
         701.0: 4,
         479.0: 28,
         844.0: 8,
         772.0: 3,
         186.0: 9,
         775.0: 19,
         267.0: 10,
         583.0: 1,
         191.0: 4,
         659.0: 4,
         586.0: 19,
         788.0: 43,
         498.0: 1,
         438.0: 4,
         815.0: 1,
         520.0: 9,
         694.0: 2,
         943.0: 1,
         794.0: 1,
         610.0: 4,
         899.0: 1,
         766.0: 3,
         687.0: 5,
         637.0: 11,
         770.0: 1,
         196.0: 1,
         588.0: 6,
         939.0: 3,
         405.0: 8,
         574.0: 6,
         593.0: 1,
         197.0: 16,
         706.0: 6,
         721.0: 1,
         703.0: 1,
         674.0: 1,
         123.0: 1,
         195.0: 4,
         254.0: 5,
         789.0: 6,
         874.0: 3,
         727.0: 3,
         261.0: 5,
         685.0: 2,
         906.0: 9,
         585.0: 3,
         204.0: 2,
         248.0: 1,
         569.0: 274,
         568.0: 153,
         567.0: 134,
         711.0: 1,
         719.0: 4,
         672.0: 8,
         566.0: 29,
         187.0: 3,
         570.0: 15,
         961.0: 1,
         777.0: 1,
         963.0: 2,
         379.0: 1,
         783.0: 1,
         648.0: 2,
         124.0: 1,
         644.0: 1})

#### Removed values that are empty and zero

## Validating PD_DESC field

In [108]:
ds_full1.distinct('KY_CD')

Counter({106.0: 11472,
         104.0: 459,
         344.0: 19937,
         None: 38,
         105.0: 5706,
         107.0: 3507,
         116.0: 509,
         114.0: 86,
         359.0: 3462,
         117.0: 4260,
         126.0: 7577,
         233.0: 2093,
         113.0: 2487,
         341.0: 9132,
         232.0: 534,
         348.0: 3995,
         235.0: 3903,
         119.0: 284,
         125.0: 610,
         351.0: 3545,
         118.0: 4135,
         358.0: 2966,
         109.0: 4760,
         236.0: 1325,
         111.0: 825,
         881.0: 1209,
         361.0: 2548,
         121.0: 3462,
         101.0: 1157,
         346.0: 279,
         350.0: 212,
         995.0: 1078,
         231.0: 292,
         353.0: 350,
         352.0: 945,
         355.0: 737,
         343.0: 1108,
         110.0: 840,
         364.0: 517,
         347.0: 1711,
         340.0: 244,
         677.0: 110,
         678.0: 52,
         112.0: 149,
         675.0: 46,
         356.0: 103,
         880.0: 23,
         124.0: 72,
         238.0: 25,
         120.0: 36,
         363.0: 67,
         578.0: 33,
         103.0: 20,
         122.0: 32,
         354.0: 56,
         365.0: 20,
         572.0: 27,
         102.0: 6,
         234.0: 30,
         345.0: 24,
         115.0: 30,
         882.0: 2,
         237.0: 6,
         230.0: 4,
         685.0: 2,
         676.0: 1,
         571.0: 4})

In [110]:
def validate_KY(data,column_name):
    data = data[data[column_name].between(100,996)]
    return data

In [111]:
data_df = validate_KY(data_df,'KY_CD')
#column8[column8['VIC_AGE_GROUP'] == ""]
data_df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,09/29/2021,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,09/27/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,09/25/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,09/25/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,09/25/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,01/06/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,01/05/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,01/01/2021,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,B,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,01/07/2021,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,01/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,K,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

In [114]:
ds_full1 = stream(data_df)
## ds_full.distinct('PD_CD')ds_full1.distinct('KY_CD')

In [117]:
ds_full1.distinct('KY_CD')

Counter({106.0: 11472,
         104.0: 459,
         344.0: 19937,
         105.0: 5706,
         107.0: 3507,
         116.0: 509,
         114.0: 86,
         359.0: 3462,
         117.0: 4260,
         126.0: 7577,
         233.0: 2093,
         113.0: 2487,
         341.0: 9132,
         232.0: 534,
         348.0: 3995,
         235.0: 3903,
         119.0: 284,
         125.0: 610,
         351.0: 3545,
         118.0: 4135,
         358.0: 2966,
         109.0: 4760,
         236.0: 1325,
         111.0: 825,
         881.0: 1209,
         361.0: 2548,
         121.0: 3462,
         101.0: 1157,
         346.0: 279,
         350.0: 212,
         995.0: 1078,
         231.0: 292,
         353.0: 350,
         352.0: 945,
         355.0: 737,
         343.0: 1108,
         110.0: 840,
         364.0: 517,
         347.0: 1711,
         340.0: 244,
         677.0: 110,
         678.0: 52,
         112.0: 149,
         675.0: 46,
         356.0: 103,
         880.0: 23,
         124.0: 72,
         238.0: 25,
         120.0: 36,
         363.0: 67,
         578.0: 33,
         103.0: 20,
         122.0: 32,
         354.0: 56,
         365.0: 20,
         572.0: 27,
         102.0: 6,
         234.0: 30,
         345.0: 24,
         115.0: 30,
         882.0: 2,
         237.0: 6,
         230.0: 4,
         685.0: 2,
         676.0: 1,
         571.0: 4})

In [119]:
ds_full1.distinct('PD_DESC')

Counter({'STRANGULATION 1ST': 2106,
         'RAPE 1': 258,
         'ASSAULT 2,1,UNCLASSIFIED': 8591,
         'ASSAULT 3': 14678,
         'ROBBERY,OPEN AREA UNCLASSIFIED': 5678,
         'BURGLARY,UNCLASSIFIED,UNKNOWN': 3208,
         'SODOMY 2': 9,
         'RAPE 3': 149,
         'ARSON 2,3,4': 81,
         'CONTEMPT,CRIMINAL': 1815,
         'CONTROLLED SUBSTANCE,SALE 3': 937,
         'PUBLIC ADMINISTRATION,UNCLASSI': 5256,
         'CHILD, ENDANGERING WELFARE': 1351,
         'FORGERY,ETC.,UNCLASSIFIED-FELO': 2444,
         'CONSPIRACY 2, 1': 103,
         'RAPE 2': 52,
         'SEXUAL ABUSE': 258,
         'LARCENY,PETIT FROM OPEN AREAS,': 9110,
         'SEXUAL ABUSE 3,2': 716,
         'RESISTING ARREST': 879,
         'STOLEN PROPERTY 3,POSSESSION': 534,
         'TRAFFIC,UNCLASSIFIED MISDEMEAN': 3728,
         'CONTROLLED SUBSTANCE, POSSESSI': 3463,
         'INTOXICATED DRIVING,ALCOHOL': 1919,
         'NY STATE LAWS,UNCLASSIFIED FEL': 558,
         'CRIMINAL MISCHIEF,UNCLASSIFIED 4': 2540,
         'MENACING,UNCLASSIFIED': 3296,
         'WEAPONS POSSESSION 1 & 2': 3461,
         'FORGERY,ETC.-MISD.': 2956,
         'LARCENY,GRAND FROM OPEN AREAS, UNATTENDED': 4100,
         'WEAPONS, POSSESSION, ETC': 1320,
         'STOLEN PROPERTY-MOTOR VEH 2ND,': 150,
         'TRAFFIC,UNCLASSIFIED INFRACTIO': 1109,
         'POSSESSION HYPODERMIC INSTRUME': 31,
         'AGGRAVATED HARASSMENT 2': 2165,
         'CRIMINAL MIS 2 & 3': 2617,
         'MANSLAUGHTER,UNCLASSIFIED - NO': 35,
         'ALCOHOLIC BEVERAGE CONTROL LAW': 279,
         'RECKLESS ENDANGERMENT 1': 580,
         'GAMBLING, DEVICE, POSSESSION': 66,
         'CONTROLLED SUBSTANCE,INTENT TO': 1852,
         'FALSE REPORT UNCLASSIFIED': 67,
         'U.S. CODE UNCLASSIFIED': 974,
         'BURGLARS TOOLS,UNCLASSIFIED': 292,
         'UNAUTHORIZED USE VEHICLE 3': 350,
         'LARCENY,GRAND BY EXTORTION': 56,
         'TRESPASS 2, CRIMINAL': 339,
         'STOLEN PROPERTY 2,1,POSSESSION': 674,
         'OBSTR BREATH/CIRCUL': 1963,
         'CRIMINAL MISCHIEF 4TH, GRAFFIT': 941,
         'ASSAULT POLICE/PEACE OFFICER': 775,
         'PUBLIC ADMINISTATION,UNCLASS M': 641,
         'RECKLESS ENDANGERMENT 2': 645,
         'TRESPASS 3, CRIMINAL': 606,
         'POSS METH MANUFACT MATERIAL': 6,
         'MISCHIEF,CRIMINAL,    UNCL 2ND': 435,
         'UNAUTH. SALE OF TRANS. SERVICE': 137,
         'LARCENY,GRAND OF AUTO': 840,
         'LARCENY,GRAND FROM PERSON,UNCL': 500,
         'THEFT OF SERVICES, UNCLASSIFIE': 940,
         'LARCENY,PETIT BY ACQUIRING LOS': 22,
         'AGGRAVATED CRIMINAL CONTEMPT': 160,
         'LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ANIMAL': 92,
         'MENACING 1ST DEGREE (VICT NOT': 129,
         'WEAPONS POSSESSION 3': 661,
         'MURDER,UNCLASSIFIED': 1122,
         'NY STATE LAWS,UNCLASSIFIED MIS': 406,
         'LEWDNESS,PUBLIC': 188,
         'BRIBERY,PUBLIC ADMINISTRATION': 178,
         'TORTURE/INJURE ANIMAL CRUELTY': 56,
         'CRIMINAL CONTEMPT 1': 440,
         'UNAUTHORIZED USE VEHICLE 2': 210,
         'SODOMY 1': 94,
         'IMPERSONATION 2, PUBLIC SERVAN': 209,
         'MISCHIEF, CRIMINAL 4, BY FIRE': 21,
         'CONTROLLED SUBSTANCE, INTENT T': 305,
         'RECKLESS DRIVING': 58,
         'CONTROLLED SUBSTANCE,POSSESS.': 506,
         'AGGRAVATED HARASSMENT 1': 70,
         'CONTROLLED SUBSTANCE,SALE 1': 54,
         'FORGERY-ILLEGAL POSSESSION,VEH': 164,
         'NY STATE LAWS,UNCLASSIFIED VIO': 110,
         'LEAVING SCENE-ACCIDENT-PERSONA': 209,
         'GAMBLING 2,PROMOTING,UNCLASSIF': 146,
         'TRESPASS 4,CRIMINAL SUB 2': 15,
         'PERJURY 3,ETC.': 82,
         'TAX LAW': 78,
         'FRAUD,UNCLASSIFIED-FELONY': 127,
         'ALCOHOLIC BEVERAGES,PUBLIC CON': 35,
         'FRAUD,UNCLASSIFIED-MISDEMEANOR': 33,
         'CONTROLLED SUBSTANCE,SALE 2': 64,
         'PROSTITUTION': 66,
         'BURGLARY,RESIDENCE,NIGHT': 299,
         'CONSPIRACY 4, 3': 43,
         'BAIL JUMPING 1 & 2': 58,
         'DRUG PARAPHERNALIA,   POSSESSE': 272,
         'OBSCENE MATERIAL - UNDER 17 YE': 36,
         'UNLICENSED OPERATOR': 17,
         'AGGRAVATED GRAND LARCENY OF ATM': 92,
         'COURSE OF SEXUAL CONDUCT AGAIN': 46,
         'SEXUAL MISCONDUCT,INTERCOURSE': 24,
         'TAMPERING 1,CRIMINAL': 376,
         'FORGERY,M.V. REGISTRATION': 40,
         'CUSTODIAL INTERFERENCE 1': 10,
         'IMPRISONMENT 2,UNLAWFUL': 84,
         'SEX CRIMES': 11,
         'SALE SCHOOL GROUNDS': 65,
         'ASSEMBLY,UNLAWFUL': 22,
         'ACCOSTING,FRAUDULENT': 25,
         'CHILD ABANDONMENT': 25,
         'CRIMINAL DISPOSAL FIREARM 1 &': 12,
         'IMPERSONATION 1, POLICE OFFICE': 18,
         'IMPRISONMENT 1,UNLAWFUL': 34,
         'PUBLIC SAFETY,UNCLASSIFIED MIS': 24,
         'SODOMY 3': 28,
         'NYS UNCLASSIFIED': 1,
         'HARASSMENT,SUBD 3,4,5': 22,
         'KIDNAPPING 2': 15,
         'HOMICIDE,NEGLIGENT,UNCLASSIFIE': 20,
         'FUGITIVE/OTHER STATES': 97,
         'MATERIAL              OFFENSIV': 95,
         'GAMBLING 1,PROMOTING,BOOKMAKIN': 23,
         'INCOMPETENT PERSON,KNOWINGLY ENDANGERING': 11,
         'CONTROLLED SUBSTANCE, SALE 5': 23,
         'FACILITATION 4, CRIMINAL': 55,
         'UNLAWFUL DISCLOSURE OF AN INTIMATE IMAGE': 13,
         'NYS PAROLE VIOLATION': 4,
         'IMPAIRED DRIVING,DRUG': 67,
         'USE OF A CHILD IN A SEXUAL PER': 9,
         'DISORDERLY CONDUCT': 27,
         'PROSTITUTION, PATRONIZING 4, 3': 37,
         'SEAT BELTS': 1,
         'GAMBLING 1,PROMOTING,POLICY': 9,
         'VEHICULAR ASSAULT (INTOX DRIVE': 37,
         'HOMICIDE, NEGLIGENT, VEHICLE,': 6,
         'ESCAPE 2,1': 6,
         'MAKING TERRORISTIC THREAT': 42,
         'PROSTITUTION 4,PROMOTING&SECUR': 24,
         'INCOMPETENT PERSON,RECKLESSY ENDANGERING': 17,
         'RECKLESS ENDANGERMENT OF PROPE': 14,
         'WEAPONS,PROHIBITED USE IMITATI': 1,
         'ADM.CODE,UNCLASSIFIED VIOLATIO': 7,
         'FACILITATION 3,2,1, CRIMINAL': 6,
         'OBSCENITY 1': 14,
         'CREDIT CARD,UNLAWFUL USE OF': 3,
         'BAIL JUMPING 3': 44,
         'PROMOTING A SEXUAL PERFORMANCE': 24,
         'ADM.CODE,UNCLASSIFIED MISDEMEA': 7,
         'END WELFARE VULNERABLE ELDERLY PERSON': 6,
         'PEDESTRIAN / UNCLASSIDIED': 3,
         'PROSTITUTION 3, PROMOTING UNDE': 2,
         'FUGITIVE/OTHER JURISDICTION NYS': 2,
         'STALKING COMMIT SEX OFFENSE': 2,
         'UNCLASSIFIED': 2,
         'FALSE ALARM FIRE': 13,
         'ESCAPE 3': 6,
         'PUBLIC HEALTH LAW,UNCLASSIFIED': 6,
         'WEAPONS,MFR,TRANSPORT,ETC.': 4,
         'JOSTLING': 4,
         'TAMPERING 3,2, CRIMINAL': 11,
         'MISCHIEF 1,CRIMINAL,EXPLOSIVE': 24,
         'NOISE,UNECESSARY': 2,
         'GENERAL BUSINESS LAW / UNCLASSIFIED': 14,
         'SEXUAL MISCONDUCT,DEVIATE': 1,
         'AGGRAVATED SEXUAL ASBUSE': 9,
         'ENTERPRISE CORRUPTION': 2,
         'HEALTH CODE,VIOLATION': 1,
         'SOLICITATION 4, CRIMINAL': 1,
         'ROBBERY,CAR JACKING': 27,
         'VIOLATION OF ORDER OF PROTECTI': 1,
         'LABOR TRAFFICKING': 1,
         'IMPAIRED DRIVING / ALCOHOL': 3,
         'THEFT OF SERVICES- CABLE TV SE': 2,
         'RIOT 2/INCITING': 6,
         'BRIBERY,COMMERCIAL': 4,
         'THEFT,RELATED OFFENSES,UNCLASS': 28,
         'CAUSE SPI/KILL ANIMAL': 8,
         'COMPUTER TAMPER/TRESSPASS': 3,
         'LURING A CHILD': 9,
         'MONEY LAUNDERING 1 & 2': 19,
         'MISCHIEF, CRIMINAL 3 & 2, OF M': 10,
         'CUSTODIAL INTERFERENCE 2': 4,
         'NUISANCE,CRIMINAL,UNCLASSIFIED': 4,
         'SEX TRAFFICKING': 19,
         'FIREWORKS, SALE': 43,
         'STOLEN PROPERTY 2,POSSESSION B': 1,
         'LARCENY,GRAND FROM BUILDING (NON-RESIDENCE) UNATTENDED': 4,
         'NEGLECT/POISON ANIMAL': 1,
         'CONTROLLED SUBSTANCE, SALE 4': 9,
         'INCEST 3': 2,
         'ONE WAY STREET': 1,
         'MANUFATURE, TRANSPORT, DEFACE, ETC...': 1,
         'LOITERING,GAMBLING,OTHER': 4,
         'PARKR&R,UNCLASSIFIED VIOLATION': 1,
         'PERJURY 2,1,ETC': 3,
         'CHILD,OFFENSES AGAINST,UNCLASS': 5,
         'HARASSMENT,SUBD 1,CIVILIAN': 11,
         'COMPUTER UNAUTH. USE/TAMPER': 1,
         'PROSTITUTION 2, UNDER 16': 6,
         'IMPROPER LIGHTS': 3,
         'LARCENY,GRAND BY THEFT OF CREDIT CARD': 8,
         'PROSTITUTION,PERMITTING': 6,
         'OBSCENITY, MATERIAL 3': 1,
         'COERCION 1': 16,
         'RECORDS,FALSIFY-TAMPER': 6,
         'BRIBERY,FRAUD': 1,
         'CHECK,BAD': 1,
         'EAVESDROPPING': 1,
         'COERCION 2': 4,
         'MISCHIEF, CRIMINAL 4, OF MOTOR': 5,
         'FIREWORKS, POSSESS/USE': 6,
         'PEDDLING,UNLAWFUL': 3,
         'FORGERY,PRESCRIPTION': 3,
         'ARSON 1': 5,
         'CHILD,LICENSED PREMISES': 2,
         'IMPAIRED DRIVING, DRUGS': 9,
         'PROSTITUTION 3,PROMOTING BUSIN': 3,
         'TRESPASS 1,CRIMINAL': 2,
         'RADIO DEVICES,UNLAWFUL POSSESS': 1,
         'MARIJUANA, SALE 4 & 5': 274,
         'MARIJUANA, POSSESSION 1, 2 & 3': 153,
         'MARIJUANA, POSSESSION 4 & 5': 134,
         'TAMPERING WITH A WITNESS': 1,
         'RIOT 1': 8,
         'MARIJUANA, POSSESSION': 29,
         'KIDNAPPING 1': 3,
         'MARIJUANA, SALE 1, 2 & 3': 15,
         'FAIL TO SIGNAL': 1,
         'SPEEDING': 2,
         'ROBBERY,GAS STATION': 1,
         'FIREWORKS PREV CONV 5 YEARS': 1,
         'PLACE FALSE BOMB': 2,
         'FALSE REPORT 1,FIRE': 1})

### Validating the LAW_CAT_CD field

In [122]:
ds_full1.distinct('LAW_CAT_CD')

Counter({'F': 52552, 'M': 61169, None: 1078, 'I': 169, 'V': 270})

In [123]:
def validate_Law(data,column_name):
    # Check if the offence column just consists of following mentioned offences
    victim_list = ["F", "M", "I", "V"]
    data = data[data[column_name].isin(victim_list)]
    return data

In [124]:
data_df = validate_Law(data_df,'LAW_CAT_CD')
#column8[column8['VIC_AGE_GROUP'] == ""]
data_df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,09/29/2021,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,09/27/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,09/25/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,09/25/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,09/25/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,01/06/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,01/05/2021,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,01/01/2021,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,B,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,01/07/2021,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,01/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,K,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

## Profiling the data to see if there are any empty values present

In [127]:
ds_full1 = stream(data_df)

In [128]:
from openclean.profiling.column import DefaultColumnProfiler

#profiles = ds.profile(default_profiler=DefaultColumnProfiler)
profiles = ds_full1.profile(default_profiler=DefaultColumnProfiler)

In [129]:
profiles.stats()

                           total  empty  distinct  uniqueness    entropy
ARREST_KEY                114160      0    114160    1.000000  16.800698
ARREST_DATE               114160      0       273    0.002391   8.048743
PD_CD                     114160      0       237    0.002076   5.366757
PD_DESC                   114160      0       228    0.001997   5.335263
KY_CD                     114160      0        65    0.000569   4.499853
OFNS_DESC                 114160      0        62    0.000543   4.302819
LAW_CODE                  114160      0       898    0.007866   6.301579
LAW_CAT_CD                114160      0         4    0.000035   1.032110
ARREST_BORO               114160      0         5    0.000044   2.173442
ARREST_PRECINCT           114160      0        77    0.000674   6.117894
JURISDICTION_CODE         114160      0        25    0.000219   0.622363
AGE_GROUP                 114160      0         5    0.000044   1.617267
PERP_SEX                  114160      0         2    0.000018   0.656236
PERP_RACE                 114160      0         7    0.000061   1.940655
X_COORD_CD                114160      0     23745    0.207998  12.426958
Y_COORD_CD                114160      0     25194    0.220690  12.497634
Latitude                  114160      0     28707    0.251463  12.633470
Longitude                 114160      0     28706    0.251454  12.633482
New Georeferenced Column  114160      0     28710    0.251489  12.633589

In [130]:
data_df.to_csv('filtered1.csv')